# coding: utf-8

"""
    IoT Device Pins Management API

    This API allows for managing the pin configurations of an IoT device.  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import testpaul2-pyth
from testpaul2-pyth.api.default_api import DefaultApi  # noqa: E501
from testpaul2-pyth.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_pins_get(self):
        """Test case for pins_get

        List all pins  # noqa: E501
        """
        pass

    def test_pins_pin_id_delete(self):
        """Test case for pins_pin_id_delete

        Delete a pin configuration  # noqa: E501
        """
        pass

    def test_pins_pin_id_get(self):
        """Test case for pins_pin_id_get

        Get a single pin configuration  # noqa: E501
        """
        pass

    def test_pins_pin_id_put(self):
        """Test case for pins_pin_id_put

        Update a pin configuration  # noqa: E501
        """
        pass

    def test_pins_post(self):
        """Test case for pins_post

        Create a new pin configuration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
