# coding: utf-8

"""
    IoT Device Pins Management API

    This API allows for managing the pin configurations of an IoT device.  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import testpaul2-pyth
from testpaul2-pyth.models.pin import Pin  # noqa: E501
from testpaul2-pyth.rest import ApiException


class TestPin(unittest.TestCase):
    """Pin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPin(self):
        """Test Pin"""
        # FIXME: construct object with mandatory attributes with example values
        # model = testpaul2-pyth.models.pin.Pin()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
