# coding: utf-8

"""
    IoT Device Pins Management API

    This API allows for managing the pin configurations of an IoT device.  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "testpaul2-pyth"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="IoT Device Pins Management API",
    author_email="",
    url="",
    keywords=["Swagger", "IoT Device Pins Management API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    This API allows for managing the pin configurations of an IoT device.  # noqa: E501
    """
)
