# coding: utf-8

"""
    IoT Device Pins Management API

    This API allows for managing the pin configurations of an IoT device.  # noqa: E501

    OpenAPI spec version: 1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from testpaul2-pyth.api_client import ApiClient


class DefaultApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def pins_get(self, **kwargs):  # noqa: E501
        """List all pins  # noqa: E501

        Retrieve a list of all pins with their current configurations.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.pins_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[Pin]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.pins_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.pins_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def pins_get_with_http_info(self, **kwargs):  # noqa: E501
        """List all pins  # noqa: E501

        Retrieve a list of all pins with their current configurations.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.pins_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[Pin]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method pins_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/pins', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Pin]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def pins_pin_id_delete(self, pin_id, **kwargs):  # noqa: E501
        """Delete a pin configuration  # noqa: E501

        Remove a pin configuration from the IoT device.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.pins_pin_id_delete(pin_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int pin_id: The ID of the pin to delete. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.pins_pin_id_delete_with_http_info(pin_id, **kwargs)  # noqa: E501
        else:
            (data) = self.pins_pin_id_delete_with_http_info(pin_id, **kwargs)  # noqa: E501
            return data

    def pins_pin_id_delete_with_http_info(self, pin_id, **kwargs):  # noqa: E501
        """Delete a pin configuration  # noqa: E501

        Remove a pin configuration from the IoT device.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.pins_pin_id_delete_with_http_info(pin_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int pin_id: The ID of the pin to delete. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['pin_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method pins_pin_id_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'pin_id' is set
        if ('pin_id' not in params or
                params['pin_id'] is None):
            raise ValueError("Missing the required parameter `pin_id` when calling `pins_pin_id_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'pin_id' in params:
            path_params['pinId'] = params['pin_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/pins/{pinId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def pins_pin_id_get(self, pin_id, **kwargs):  # noqa: E501
        """Get a single pin configuration  # noqa: E501

        Retrieve the configuration of a specific pin by its ID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.pins_pin_id_get(pin_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int pin_id: The ID of the pin to retrieve. (required)
        :return: Pin
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.pins_pin_id_get_with_http_info(pin_id, **kwargs)  # noqa: E501
        else:
            (data) = self.pins_pin_id_get_with_http_info(pin_id, **kwargs)  # noqa: E501
            return data

    def pins_pin_id_get_with_http_info(self, pin_id, **kwargs):  # noqa: E501
        """Get a single pin configuration  # noqa: E501

        Retrieve the configuration of a specific pin by its ID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.pins_pin_id_get_with_http_info(pin_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int pin_id: The ID of the pin to retrieve. (required)
        :return: Pin
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['pin_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method pins_pin_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'pin_id' is set
        if ('pin_id' not in params or
                params['pin_id'] is None):
            raise ValueError("Missing the required parameter `pin_id` when calling `pins_pin_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'pin_id' in params:
            path_params['pinId'] = params['pin_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/pins/{pinId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Pin',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def pins_pin_id_put(self, body, pin_id, **kwargs):  # noqa: E501
        """Update a pin configuration  # noqa: E501

        Update the configuration of an existing pin.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.pins_pin_id_put(body, pin_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Pin body: (required)
        :param int pin_id: The ID of the pin to update. (required)
        :return: Pin
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.pins_pin_id_put_with_http_info(body, pin_id, **kwargs)  # noqa: E501
        else:
            (data) = self.pins_pin_id_put_with_http_info(body, pin_id, **kwargs)  # noqa: E501
            return data

    def pins_pin_id_put_with_http_info(self, body, pin_id, **kwargs):  # noqa: E501
        """Update a pin configuration  # noqa: E501

        Update the configuration of an existing pin.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.pins_pin_id_put_with_http_info(body, pin_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Pin body: (required)
        :param int pin_id: The ID of the pin to update. (required)
        :return: Pin
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'pin_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method pins_pin_id_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `pins_pin_id_put`")  # noqa: E501
        # verify the required parameter 'pin_id' is set
        if ('pin_id' not in params or
                params['pin_id'] is None):
            raise ValueError("Missing the required parameter `pin_id` when calling `pins_pin_id_put`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'pin_id' in params:
            path_params['pinId'] = params['pin_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/pins/{pinId}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Pin',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def pins_post(self, body, **kwargs):  # noqa: E501
        """Create a new pin configuration  # noqa: E501

        Add a new pin configuration to the IoT device.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.pins_post(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Pin body: (required)
        :return: Pin
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.pins_post_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.pins_post_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def pins_post_with_http_info(self, body, **kwargs):  # noqa: E501
        """Create a new pin configuration  # noqa: E501

        Add a new pin configuration to the IoT device.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.pins_post_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Pin body: (required)
        :return: Pin
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method pins_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `pins_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/pins', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Pin',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
